### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by lfzm** [OrleansContrib/Orleans.MultiClient#2]
@galvesribeiro Hello, i really want to manage this library, please help me handle it

**Comment by galvesribeiro** [comment]
Sure, how can I help?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lfzm** [comment]
@galvesribeiro Is it possible to set as a member of this repository

**Comment by lfzm** [comment]
@galvesribeiro How do I deal with PR? I really don't think I have permission to deal with it.

**Comment by galvesribeiro** [comment]
you was added as Admin on this project and GitHub should have send an email to you with a link

![image](https://user-images.githubusercontent.com/4714040/76218950-0eae5d00-61e3-11ea-9c75-49f9d3b0cd20.png)

In case you missed it, please check this link and accept the invitation https://github.com/OrleansContrib/Orleans.MultiClient/invitations

**Comment by lfzm** [comment]
@galvesribeiro Sorry, I didn't see the email.
This invitation has expired.Please re-invite, thank you

**Comment by galvesribeiro** [comment]
@lfzm just sent again

**Comment by lfzm** [comment]
@galvesribeiro thank you
